version: "3"
services:

  db:
    image: jenkins/jenkins:latest
    container_name: jenkins
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 8080:8080
      - 50000:50000


