version: "3"
services:

  db:
    image: mysql:8.0.22
    container_name: mysql
    command: 
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes: 
      - ./data:/var/lib/mysql